/*
 Generated by typeshare 1.7.0
*/

export interface Metadata {
	param_a: string;
	param_b: number;
	param_c: boolean;
}

/** Test doc */
export interface User {
	name: string;
	email: string;
	age: number;
	metadata: Metadata;
}

