/* eslint-disable */
// @ts-nocheck
/*    @@@@@@@@@@@@@ & ###############
   @@@@@@@@@@@@@@ &&& ###############
 @@@@@@@@@@@@@@ &&&&& ###############
############### &&&&& ###############
######## Generated by Qubit! ########
############### &&&&& ###############
############### &&&&& @@@@@@@@@@@@@@
############### && @@@@@@@@@@@@@@
############### & @@@@@@@@@@@@@    */

import type { Query, Mutation, Subscription } from "@qubit-rs/client";
export type QubitServer = { get_name: Query<[], string>, list_messages: Subscription<[], Array<ChatMessage>>, list_online: Subscription<[], Array<string>>, send_message: Mutation<[message: string], null>, };

