/* eslint-disable */
// @ts-nocheck
/*
      @@@@@@@@@@@@@ & ###############
   @@@@@@@@@@@@@@ &&& ###############
 @@@@@@@@@@@@@@ &&&&& ###############
############### &&&&& ###############
######## Generated by Qubit! ########
############### &&&&& ###############
############### &&&&& @@@@@@@@@@@@@@
############### && @@@@@@@@@@@@@@
############### & @@@@@@@@@@@@@

*/
import type { Query, Mutation, Subscription } from "@qubit-rs/client";
export type QubitServer = { echo_cookie: Query<[], string>, secret_endpoint: Query<[], string>, };
