/* eslint-disable */
// @ts-nocheck
/*
      @@@@@@@@@@@@@ & ###############
   @@@@@@@@@@@@@@ &&& ###############
 @@@@@@@@@@@@@@ &&&&& ###############
############### &&&&& ###############
######## Generated by Qubit! ########
############### &&&&& ###############
############### &&&&& @@@@@@@@@@@@@@
############### && @@@@@@@@@@@@@@
############### & @@@@@@@@@@@@@

*/
import type { Query, Mutation, Subscription } from "@qubit-rs/client";
export type QubitServer = { add: Mutation<[n: number], null>, countdown: Subscription<[], number>, decrement: Mutation<[], null>, get: Query<[], number>, increment: Mutation<[], null>, };
