// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NestedStruct } from "./NestedStruct";

export type MyEnum = "A" | { "B": number } | { "C": { field: number, } } | { "D": NestedStruct };