// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "./Metadata";

export type User = { name: string, email: string, age: number, metadata: Metadata, };