[package]
name = "rstrpc-macros"
version = "0.0.1"
edition = "2021"
description = "Macros to accompany `rstrpc`."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.76"
quote = "1.0.35"
syn = "2.0.48"
ts-rs = "7.1.1"
