name: checks

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
      - run: pnpm i
      - run: pnpm lint --error-on-warnings

  typecheck:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - packages/client
          - examples/authentication/auth-demo
          - examples/chaos
          - examples/chat-room-react
          - examples/counter
          - examples/hello-world

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm i
      - run: pnpm tsc

  clippy:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - '.'
          - examples/authentication
          - examples/chaos
          - examples/chat-room-react/src-rust
          - examples/counter
          - examples/hello-world

    env:
      RUSTFLAGS: "-Dwarnings" # Fail on warnings
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy
