[package]
name = "qubit-macros"
version = "0.6.5"
edition = "2021"
description = "Macros to accompany `qubit`."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"
ts-rs = "10.1.0"
